# fly.toml app configuration file generated for task-manager on 2024-01-21T12:53:41-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "task-manager"
primary_region = "gru"
kill_signal = "SIGTERM"

[build]

[env]
  PHX_HOST = "task-manager.fly.dev"
  PORT = "8080"
  DATABASE_PATH = "/mnt/database/database.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source="database"
  destination="/mnt/database"
